flowchart BT

coreAudioApi["Core Audio<br>(Windows API)"]

subgraph scannerBackend["Sound Scanner Backend"]
    goCgoWrapper["SoundLibWrap<br>(Go/CGO module)"]
    soundAgentApiDll["SoundAgentApi.dll<br>(ANSI C API)"]
    soundDeviceCollection["SoundAgentLib::<br>SoundDeviceCollection<br>(C++ class)"]
end

coreAudioApi ==> |Device and volume change<br>notifications| soundDeviceCollection
soundDeviceCollection --> |Read device characteristics| coreAudioApi

winSoundScannerService["<b>WinSoundScanner<br>(Go Windows Service)</b>"]
requestQueue[("Request Queue<br>(RabbitMQ channel)")]
rabbitMqRestForwarder["RabbitMQ-to-REST Forwarder<br>(.NET microservice)"]
deviceRepositoryApi["Device Repository Server<br>(REST API)"]

winSoundScannerService --> |Access device| goCgoWrapper
goCgoWrapper ==> |Device events| winSoundScannerService

goCgoWrapper --> |Call C API| soundAgentApiDll
soundAgentApiDll --> |Call C++ API| soundDeviceCollection

soundDeviceCollection ==> |SaaEvent callbacks| soundAgentApiDll
soundAgentApiDll ==> |CGO callbacks| goCgoWrapper

winSoundScannerService ==> |Enqueue request messages| requestQueue

requestQueue ==> |Fetch request messages| rabbitMqRestForwarder
rabbitMqRestForwarder --> |Detect request messages| requestQueue
rabbitMqRestForwarder ==> |Forward request messages| deviceRepositoryApi
