flowchart BT

coreAudioApi["Core Audio<br>(Windows API)"]

subgraph soundWinAgentModule["SoundWinAgent C++ Module"]
    soundDeviceCollection["SoundAgentLib::<br>SoundDeviceCollection<br>(C++ class)"]
    soundWinAgentService["<b>SoundWinAgent<br>(C++ Windows Service)</b>"]
    rabbitMqHttpRequestDispatcher["RabbitMqHttpRequestDispatcher<br>(C++ class)"]

    soundWinAgentService --> |Access device| soundDeviceCollection
    soundDeviceCollection ==> |Device events| soundWinAgentService

    soundWinAgentService --> |Enqueue request messages| rabbitMqHttpRequestDispatcher
end

coreAudioApi ==> |Device and volume change<br>notifications| soundDeviceCollection
soundDeviceCollection --> |Read device characteristics| coreAudioApi

requestQueue[("Request Queue<br>(RabbitMQ channel)")]
rabbitMqRestForwarder["RabbitMQ-to-REST Forwarder<br>(.NET microservice)"]
deviceRepositoryApi["Device Repository Server<br>(REST API)"]

rabbitMqHttpRequestDispatcher ==> |Enqueue request messages| requestQueue


requestQueue ==> |Fetch request messages| rabbitMqRestForwarder
rabbitMqRestForwarder --> |Detect request messages| requestQueue

rabbitMqRestForwarder ==> |Forward request messages| deviceRepositoryApi
