flowchart BT

classDef dottedBox fill:transparent, fill-opacity:0.55, stroke-dasharray:10 8, stroke-width:2px;
classDef stressedBox fill:#f0f0f0, fill-opacity:0.2, stroke-dasharray:10 8, stroke-width:4px;

coreAudioApi["Core Audio<br>(Windows API)"]

subgraph soundWinAgentModule["SoundWinAgent Monolith"]
    soundDeviceCollection["SoundAgentLib::<br>SoundDeviceCollection<br>(C++ class)"]
    soundWinAgentService["<b>SoundWinAgent<br>(C++ Windows Service)</b>"]
    rabbitMqHttpRequestDispatcher["RabbitMqHttpRequestDispatcher<br>(C++ class)"]

    soundWinAgentService --> |Access device| soundDeviceCollection
    soundDeviceCollection --> |Device events| soundWinAgentService

    soundWinAgentService --> |Enqueue request messages| rabbitMqHttpRequestDispatcher
end
class soundWinAgentModule stressedBox

coreAudioApi --> |Device and volume change<br>notifications| soundDeviceCollection
soundDeviceCollection --> |Read device characteristics| coreAudioApi

subgraph requestQueueMicroservice["<br>"]
    requestQueue[("Request Queue<br>(RabbitMQ channel)")]
    rabbitMqRestForwarder["RmqToRestApiForwarder<br>(.NET microservice)"]
end
class requestQueueMicroservice dottedBox

deviceRepositoryApi["Device Repository Server<br>(REST API)"]

rabbitMqHttpRequestDispatcher --> |Enqueue request messages| requestQueue


requestQueue --> |Fetch request messages| rabbitMqRestForwarder
rabbitMqRestForwarder --> |Detect request messages| requestQueue

rabbitMqRestForwarder --> |POST/PUT requests| deviceRepositoryApi
