flowchart BT
  classDef edgeLabel fill:#f6f8fa,stroke:#57606a,stroke-width:1px,color:#24292f,font-size:11px;
  classDef transparent fill:none,stroke:none;
%%  classDef startPoint fill:#d4edda,stroke:#28a745,stroke-width:2px;
  classDef startPoint fill:#f6f8fa,stroke:#57606a,stroke-width:2px,color:#24292f;
  classDef default fill:#f6f8fa,stroke:#57606a,color:#24292f;
  classDef bold fill:#f6f8fa,stroke:#57606a,stroke-width:3px,color:#24292f;
  classDef boldbold fill:#f6f8fa,stroke:#57606a,stroke-width:5px,color:#24292f;

subgraph LEFT["#10;"]
  WIN["Core Audio<br>(Windows API)"]:::bold

  subgraph BCK["sound-win-scanner backend"]
	WRAP["soundlibwrap<br>(Go/CGO Module)"]:::bold
	DLL["SoundAgentApi.dll<br>(ANSI C API)"]:::bold
	LIB["SoundAgentLib,<br>SoundDeviceCollection<br>(C++ class)"]:::bold
  end
  style BCK fill:#f6f8fa,stroke:#57606a,color:#24292f


  APP --> |ACCESS device| WRAP
  WRAP ==> |Device <b>EVENTS</b>| APP 

  WRAP --> |ACCESS C API| DLL
  DLL --> |ACCESS C++ API| LIB

  LIB ==>|SaaEvent <b>CALLBACKS</b>| DLL
  DLL ==>|CGO <b>CALLBACKS</b>| WRAP

  WIN ==> |Device and volume change<br>NOTIFICATIONS| LIB
  LIB --> |ACCESS device charachteristics| WIN

end
class LEFT transparent

subgraph RIGHT["#10;"]
  APP["<b>WinSoundScanner<br>Windows Service<br>(Go Module)</b>"]:::boldbold
  CHAN(["RMQ Channel"]):::bold
  APP ==> |EQUEUE Requests| CHAN
end
class RIGHT transparent


