flowchart BT

WIN["Core Audio<br>(Windows API)"]

subgraph BCK["SoundWinAgent C++ module"]
	LIB["SoundAgentLib,<br>SoundDeviceCollection<br>(C++ class)"]
	HTTPPROC["HttpRequestDispatcher<br>(C++ class)"]

	APP["<b>SoundWinAgent<br>(C++ Windows Service)</b>"]
	CQUEUE["Internal C++ request queue"]

	APP --> |ENQUEUE message requests| HTTPPROC
end
style BCK fill:#f6f8fa,stroke:#57606a,color:#24292f

WIN ==> |Device and volume change<br>NOTIFICATIONS| LIB
LIB --> |ACCESS device characteristics| WIN

API["Device Repository Server<br>(REST API)"]

APP --> |ACCESS device| LIB
LIB ==> |Device <b>EVENTS</b>| APP

HTTPPROC --> |PUSH request| CQUEUE
CQUEUE ==> |POST/PUT requests| API
