name: Release Windows container

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Fetch native assets (.zip) and extract
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $ErrorActionPreference = "Stop"
          New-Item -ItemType Directory -Force -Path native\include | Out-Null
          New-Item -ItemType Directory -Force -Path native\lib | Out-Null
          New-Item -ItemType Directory -Force -Path runtime | Out-Null
          New-Item -ItemType Directory -Force -Path tmp | Out-Null

          # Download zip from SoundWinAgent release
          $zipName = "soundagent-go-$env:VERSION.zip"
          try {
            gh release download "$env:VERSION" -R "eduarddanziger/SoundWinAgent" -p $zipName -D tmp | Out-Null
          } catch {
            gh release download "$env:VERSION" -R "eduarddanziger/SoundWinAgent" -p "soundagent-go-*.zip" -D tmp | Out-Null
          }

          $zipPath = Get-ChildItem tmp -Filter "soundagent-go-*.zip" | Select-Object -First 1 -ExpandProperty FullName
          if (-not $zipPath) { throw "Zip asset 'soundagent-go-*.zip' not found on tag $env:VERSION in eduarddanziger/SoundWinAgent." }

          $extractDir = Join-Path $PWD "tmp\extracted"
          New-Item -ItemType Directory -Force -Path $extractDir | Out-Null
          Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force

          # Locate files
          $h   = Get-ChildItem -Path $extractDir -Recurse -Filter "SoundAgentApi.h" | Select-Object -First 1
          $lib = Get-ChildItem -Path $extractDir -Recurse -Filter "SoundAgentApiDll.lib" | Select-Object -First 1
          $dll = Get-ChildItem -Path $extractDir -Recurse -Filter "SoundAgentApiDll.dll" | Select-Object -First 1

          if (-not $h)   { throw "Header 'SoundAgentApi.h' not found in the zip." }
          if (-not $lib) { throw "Library 'SoundAgentApiDll.lib' not found in the zip." }
          if (-not $dll) { throw "DLL 'SoundAgentApiDll.dll' not found in the zip." }

          # Copy into module layout
          Copy-Item $h.FullName   native\include\SoundAgentApi.h -Force
          Copy-Item $lib.FullName native\lib\SoundAgentApiDll.lib -Force
          Copy-Item $dll.FullName runtime\SoundAgentApiDll.dll -Force

      - name: Build app (CGO)
        shell: pwsh
        env:
          CGO_ENABLED: "1"
        run: |
          $ErrorActionPreference = "Stop"
          $env:CGO_CFLAGS  = "-Inative\include"
          $env:CGO_LDFLAGS = "-Lnative\lib -lSoundAgentApiDll"

          New-Item -ItemType Directory -Force -Path out | Out-Null
          # TODO: set your main package path below
          go build -trimpath -o out\app.exe ./cmd/yourapp

          Copy-Item runtime\SoundAgentApiDll.dll out\SoundAgentApiDll.dll -Force

      - name: Write Dockerfile
        shell: pwsh
        run: |
          @'
          # escape=`
          FROM mcr.microsoft.com/windows/servercore:ltsc2022
          SHELL ["pwsh","-Command","$ErrorActionPreference='Stop';"]
          WORKDIR C:\app
          COPY .\out\app.exe C:\app\app.exe
          COPY .\out\SoundAgentApiDll.dll C:\app\SoundAgentApiDll.dll
          ENTRYPOINT ["C:\\app\\app.exe"]
          '@ | Set-Content -Encoding UTF8 -Path Dockerfile

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push image
        shell: pwsh
        run: |
          docker build --tag "$env:IMAGE_NAME:$env:VERSION" --tag "$env:IMAGE_NAME:latest" .
          docker push "$env:IMAGE_NAME:$env:VERSION"
          docker push "$env:IMAGE_NAME:latest"